package com.rafael.vr.ui;

import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class MenuForm extends JFrame {
    private JButton btnVenda;
    private JPanel panel1;
    private JButton btnProdutos;
    private JButton btnClientes;

    public MenuForm() {
        btnProdutos.addActionListener(e -> openProductForm());
        btnClientes.addActionListener(e -> openCustomerForm());
        btnVenda.addActionListener(e -> openSaleForm());
    }

    private void openProductForm() {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Cadastro de Produtos");
            frame.setContentPane(new ProductForm().getPanel1());
            frame.setSize(400, 300);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setVisible(true);
        });
    }

    private void openCustomerForm() {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Cadastro de Clientes");
            frame.setContentPane(new CustomerForm().getPanel1());
            frame.setSize(400, 300);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setVisible(true);
        });
    }

    private void openSaleForm() {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Venda");
            frame.setContentPane(new SaleForm().getPanel1());
            frame.setSize(400, 500);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setVisible(true);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        btnVenda = new JButton();
        btnVenda.setText("Venda");
        panel1.add(btnVenda, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnProdutos = new JButton();
        btnProdutos.setText("Produtos");
        panel1.add(btnProdutos, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnClientes = new JButton();
        btnClientes.setText("Clientes");
        panel1.add(btnClientes, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
