package com.rafael.vr.ui;

import com.rafael.vr.dao.ProductDao;
import com.rafael.vr.model.Product;
import lombok.Data;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;

import static com.rafael.vr.util.DialogUtil.showError;
import static com.rafael.vr.util.DialogUtil.showSuccess;
import static java.util.Objects.isNull;

@Data
public class ProductForm {
    private JPanel panel1;
    private JTextField txtCodigo;
    private JTextField txtDescricao;
    private JTextField txtPreco;
    private JButton btnPesquisar;
    private JLabel lblCodigo;
    private JLabel lblDescricao;
    private JLabel lblPreco;
    private JButton btnExcluir;
    private JButton btnSalvar;
    private JButton btnNovo;

    private ProductDao productDao = new ProductDao();

    public ProductForm() {
        btnSalvar.addActionListener(e -> save());
        btnNovo.addActionListener(e -> newProduct());
        btnPesquisar.addActionListener(e -> find());
        btnExcluir.addActionListener(e -> delete());
    }

    private void save() {
        var product = Product.builder()
                .description(txtDescricao.getText())
                .price(new BigDecimal(txtPreco.getText()))
                .code(txtCodigo.getText().isEmpty() ? null : Integer.parseInt(txtCodigo.getText()))
                .build();
        try {
            if (isNull(product.getCode())) {
                product = productDao.create(product);
                txtCodigo.setText(product.getCode().toString());
                showSuccess("Produto criado com sucesso!");
                return;
            }
            productDao.update(product);
            showSuccess("Produto atualizado com sucesso!");
        } catch (RuntimeException e) {
            showError(e.getMessage());
        }
    }

    private void delete() {
        try {
            productDao.delete(Integer.parseInt(txtCodigo.getText()));
            reset();
            showSuccess("Produto excluído com sucesso!");
        } catch (RuntimeException e) {
            showError(e.getMessage());
        }
    }

    private void find() {
        if (!txtCodigo.isEnabled()) {
            reset();
            return;
        }
        var code = Integer.parseInt(txtCodigo.getText());
        var product = productDao.findBycode(code);
        if (isNull(product)) {
            showError("Produto não encontrado");
            return;
        }
        txtDescricao.setText(product.getDescription());
        txtPreco.setText(product.getPrice().toString());
        found();
    }

    private void reset() {
        txtCodigo.setText("");
        txtCodigo.setEnabled(true);
        txtDescricao.setEnabled(false);
        txtPreco.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtDescricao.setText("");
        txtPreco.setText("");
    }

    private void found() {
        txtCodigo.setEnabled(false);
        txtDescricao.setEnabled(true);
        txtPreco.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }

    private void newProduct() {
        txtCodigo.setText("");
        txtCodigo.setEnabled(false);
        txtDescricao.setEnabled(true);
        txtPreco.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        txtDescricao.setText("");
        txtPreco.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        txtCodigo = new JTextField();
        panel1.add(txtCodigo, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblDescricao = new JLabel();
        lblDescricao.setText("Descrição");
        panel1.add(lblDescricao, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblPreco = new JLabel();
        lblPreco.setText("Preço");
        panel1.add(lblPreco, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtDescricao = new JTextField();
        txtDescricao.setEnabled(false);
        panel1.add(txtDescricao, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtPreco = new JTextField();
        txtPreco.setEnabled(false);
        panel1.add(txtPreco, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblCodigo = new JLabel();
        lblCodigo.setText("Código");
        panel1.add(lblCodigo, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnPesquisar = new JButton();
        btnPesquisar.setText("Pesquisar");
        panel1.add(btnPesquisar, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnExcluir = new JButton();
        btnExcluir.setEnabled(false);
        btnExcluir.setText("Excluir");
        panel1.add(btnExcluir, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSalvar = new JButton();
        btnSalvar.setEnabled(false);
        btnSalvar.setText("Salvar");
        panel1.add(btnSalvar, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnNovo = new JButton();
        btnNovo.setText("Novo");
        panel1.add(btnNovo, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
